language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
script: inv test
after_success: coveralls
notifications:
  email: false
install:
  # Coveralls 4.0 doesn't support Python 3.2
  - pip install -r requirements.txt
  - pip install python-coveralls
